[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.4.2"
wit-bindgen-rt = "0.20.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:rust"

[package.metadata.component.dependencies]
